### ISSUE TITLE
Crash when creating new world - 1.7

### ISSUE THREAD

**Issue by jimmyh77** [NOVA-Team/NOVA-Template#4]
I can recreate this every time by just downloading this template, doing "./gradlew idea" and then loading up idea and running the "17" client.

http://pastebin.com/y6VYvQyD

**Comment by RX14** [comment]
This is clearly a wrapper bug, why are you assigning me? If it was deobf it wouldn't even launch!

**Comment by RX14** [comment]
It's a wrapper bug, does this look like the wrapper repo to you?
